using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace GdsSharp.SourceGenerators.New
{
    [Generator]
    public class GdsRecordGenerator : ISourceGenerator
    {
        public void Initialize(GeneratorInitializationContext context)
        {
            context.RegisterForSyntaxNotifications(() => new RecordSyntaxReceiver());
        }

        public void Execute(GeneratorExecutionContext context)
        {
            if (!(context.SyntaxReceiver is RecordSyntaxReceiver receiver))
            {
                return;
            }

            foreach (var candidate in receiver.Candidates)
            {
                Console.WriteLine($"Generating GdsRecord for {candidate.Identifier.Text}");
                var model = context.Compilation.GetSemanticModel(candidate.SyntaxTree);
                if (!(model.GetDeclaredSymbol(candidate) is INamedTypeSymbol classSymbol))
                    continue;

                if (!classSymbol.GetAttributes().Any(ad => ad.AttributeClass?.Name.Contains(nameof(BigEndianAttribute)) ?? false))
                {
                    continue;
                }

                var source = GenerateGdsRecordSource(classSymbol);
                context.AddSource($"{classSymbol.Name}_GdsGenerated.Generated.cs", SourceText.From(source, Encoding.UTF8));
            }
        }

        private static readonly string[] Usings = {
            "System",
            "System.Buffers.Binary"
        };
        
        private static string GenerateGdsRecordSource(INamedTypeSymbol structSymbol)
        {
            var namespaceName = structSymbol.ContainingNamespace.ToDisplayString();
            var className = structSymbol.Name;

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            foreach (var @using in Usings)
            {
                sb.AppendLine($"using {@using};");
            }
            sb.AppendLine($"namespace {namespaceName}");
            sb.AppendLine("{");
            sb.AppendLine($"    public partial struct {className}");
            sb.AppendLine("    {");

            foreach (var member in structSymbol.GetMembers().OfType<IFieldSymbol>())
            {
                var newFieldName = char.ToUpper(member.Name[1]) + member.Name.Substring(2);

                // Check if the field has a BigEndian attribute or is private and starts with an underscore
                if (member.GetAttributes().FirstOrDefault(ad => ad.AttributeClass?.Name.Contains(nameof(BigEndianAttribute)) ?? false) is AttributeData attr)
                {
                    if(attr.ConstructorArguments.Length == 1 && attr.ConstructorArguments[0].Value is string name)
                    {
                        newFieldName = name;
                    }
                }
                else
                {
                    if (member.DeclaredAccessibility != Accessibility.Private) continue;
                    if (!member.Name.StartsWith("_")) continue;
                }
                
                var typeName = member.Type.ToDisplayString();

                sb.AppendLine($"    public {typeName} {newFieldName} => BinaryPrimitives.ReverseEndianness({member.Name});");
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");
            return sb.ToString();
        }
    }

    public class RecordSyntaxReceiver : ISyntaxReceiver
    {
        public List<StructDeclarationSyntax> Candidates { get; } = new List<StructDeclarationSyntax>();

        public void OnVisitSyntaxNode(SyntaxNode syntaxNode)
        {
            if (syntaxNode is StructDeclarationSyntax cds &&
                cds.Modifiers.Any(m => m.IsKind(Microsoft.CodeAnalysis.CSharp.SyntaxKind.PartialKeyword)))
            {
                Candidates.Add(cds);
            }
        }
    }
}