using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace GdsSharp.SourceGenerators
{
    [Generator]
    public class GdsAutoPopulateGenerator : ISourceGenerator
    {
        public void Initialize(GeneratorInitializationContext context)
        {
            // attach debugger
            // Debugger.Launch();
            context.RegisterForSyntaxNotifications(() => new GdsSyntaxReceiver());
        }

        public void Execute(GeneratorExecutionContext context)
        {
            // Retrieve the syntax receiver (it was created in Initialize)
            if (!(context.SyntaxReceiver is GdsSyntaxReceiver receiver))
            {
                return;
            }

            // Get the symbol for the GdsRecordAttribute so we can filter types.
            var attributeSymbol = context.Compilation.GetTypeByMetadataName(nameof(GdsAutoPopulateAttribute));

            foreach (var candidate in receiver.CandidateClasses)
            {
                Console.WriteLine($"Generating GdsRecord for {candidate.Identifier.Text}");
                var model = context.Compilation.GetSemanticModel(candidate.SyntaxTree);
                if (!(model.GetDeclaredSymbol(candidate) is INamedTypeSymbol classSymbol))
                    continue;

                // Only process classes that have [GdsRecord] applied.
                if (!classSymbol.GetAttributes().Any(ad => ad.AttributeClass?.Name.Contains(nameof(GdsAutoPopulateAttribute)) ?? false))
                {
                    continue;
                }

                // Generate the source code for this class.
                var source = GenerateGdsRecordSource(classSymbol);
                context.AddSource($"{classSymbol.Name}_GdsGenerated.cs", SourceText.From(source, Encoding.UTF8));
            }
        }

        private string GenerateGdsRecordSource(INamedTypeSymbol classSymbol)
        {
            var namespaceName = classSymbol.ContainingNamespace.ToDisplayString();
            var className = classSymbol.Name;

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("using System;");
            sb.AppendLine("using GdsSharp.Lib.Terminals.Abstractions;\nusing GdsSharp.SourceGenerators;using GdsSharp.Lib.Binary;");
            sb.AppendLine($"namespace {namespaceName}");
            sb.AppendLine("{");
            sb.AppendLine($"    public partial class {className} : IGdsReadableRecord");
            sb.AppendLine("    {");

            // Generate the Read method.
            sb.AppendLine("        public void Read(GdsBinaryReader reader, GdsHeader header)");
            sb.AppendLine("        {");
            foreach (var member in classSymbol.GetMembers().OfType<IPropertySymbol>())
            {
                // Only generate code for public properties with a setter.
                if (member.SetMethod == null || member.DeclaredAccessibility != Accessibility.Public)
                    continue;

                string propertyName = member.Name;
                string typeName = member.Type.ToDisplayString();

                // Choose the correct read call based on the property type.
                string readCall;
                switch (typeName)
                {
                    case "ushort":
                        readCall = "reader.ReadUInt16()";
                        break;
                    case "uint":
                        readCall = "reader.ReadUInt32()";
                        break;
                    case "short":
                        readCall = "reader.ReadInt16()";
                        break;
                    case "int":
                        readCall = "reader.ReadInt32()";
                        break;
                    case "string":
                        readCall = "reader.ReadAsciiString(header.NumToRead)";
                        break;
                    case "float":
                        readCall = "reader.ReadSingle()";
                        break;
                    case "double":
                        readCall = "reader.ReadDouble()";
                        break;
                    default:
                        throw new NotSupportedException($"Type '{typeName}' is not supported in GDS records.");
                }

                sb.AppendLine($"            this.{propertyName} = {readCall};");
            }

            sb.AppendLine("        }");

            // Generate the Write method.
            sb.AppendLine("        public void Write(GdsBinaryWriter writer)");
            sb.AppendLine("        {");
            foreach (var member in classSymbol.GetMembers().OfType<IPropertySymbol>())
            {
                // Only generate code for public properties with a getter.
                if (member.GetMethod == null || member.DeclaredAccessibility != Accessibility.Public)
                    continue;

                string propertyName = member.Name;
                string typeName = member.Type.ToDisplayString();

                // Write call based on property type.
                // For most types, it's a simple call.
                string writeCall;
                switch (typeName)
                {
                    case "ushort":
                    case "uint":
                    case "short":
                    case "int":
                    case "string":
                    case "float":
                    case "double":
                    case "ulong":
                    case "long":
                        writeCall = $"writer.Write(this.{propertyName});";
                        break;
                    default:
                        throw new NotSupportedException($"Type '{typeName}' is not supported in GDS records.");
                }

                sb.AppendLine($"            {writeCall}");
            }

            sb.AppendLine("        }");

            sb.AppendLine("    }");
            sb.AppendLine("}");
            return sb.ToString();
        }
    }

    public class GdsSyntaxReceiver : ISyntaxReceiver
    {
        public List<ClassDeclarationSyntax> CandidateClasses { get; } = new List<ClassDeclarationSyntax>();

        public void OnVisitSyntaxNode(SyntaxNode syntaxNode)
        {
            if (syntaxNode is ClassDeclarationSyntax cds &&
                cds.Modifiers.Any(m => m.IsKind(Microsoft.CodeAnalysis.CSharp.SyntaxKind.PartialKeyword)))
            {
                CandidateClasses.Add(cds);
            }
        }
    }
}